import { User, SprintClass, Deliverable, Certificate } from './types';

export const CURRENT_USER: User = {
  id: 'user-current',
  name: 'Temuulen Batbayar',
  email: 'temuulen@mentor.mn',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  gender: 'Male',
  age: 17,
  grade: '12th Grade',
  school: 'School No. 1, Ulaanbaatar',
  location: 'Ulaanbaatar - Sukhbaatar District',
  specializations: ['Python & Pygame', 'Cambridge AS Math', 'Intro to Algorithms'],
  learningGoals: ['National Physics Olympiad', 'Advanced Calculus'],
  mentorStatus: 'verified',
  achievements: [
    'National Informatics Olympiad Silver Medal 2025',
    'Cambridge AS Mathematics: A* (Score 96)',
    'SAT: 1520 (Math 800)',
  ],
  mentorTier: 'SENIOR_MENTOR',
  mentorXp: 220,
  totalStudentsMentored: 8,
  completedClasses: 3,
  enrolledClassIds: ['class-3'],
};

export const INITIAL_CLASSES: SprintClass[] = [
  {
    id: 'class-1',
    title: 'Cambridge AS Pure Mathematics: Differentiation & Mechanics',
    description: 'A focused 2-week sprint covering chain rule, rates of change, and Newtonian kinematics with past Cambridge paper problems.',
    mentorId: 'mentor-1',
    mentorName: 'Anand Enkhbold',
    mentorTier: 'SENIOR_MENTOR',
    mentorSchool: 'Orchlon International School',
    subject: 'Mathematics',
    curriculum: 'Cambridge AS/A-Level',
    maxSeats: 3,
    priceMnt: 0,
    enrollmentMode: 'instant',
    missions: [
      {
        weekNumber: 1,
        title: 'Chain Rule & Optimization Proofs',
        description: 'Deep dive into differentiation definitions and rate-of-change challenges.',
        deliverablePrompt: 'Submit solved PDF of 8 multi-part Cambridge Mechanics problems.',
      },
      {
        weekNumber: 2,
        title: 'Newtonian Kinematics & Applied Trajectories',
        description: 'Apply calculus to projectile motion and energy conservation.',
        deliverablePrompt: 'Submit annotated solutions to Cambridge 2024 past paper section B.',
      },
    ],
    enrolledStudents: [
      {
        id: 'std-1',
        name: 'Munkhjin Altangerel',
        school: 'Khovd 1st General School',
        location: 'Khovd Aimag',
        grade: '11th Grade',
        enrolledAt: '2026-09-18T10:00:00Z',
        status: 'confirmed',
      },
      {
        id: 'std-2',
        name: 'Enerel Bayarsaikhan',
        school: 'Sant School',
        location: 'Ulaanbaatar - Bayanzurkh',
        grade: '11th Grade',
        enrolledAt: '2026-09-19T14:30:00Z',
        status: 'confirmed',
      },
    ],
    startDate: '2026-09-24',
    endDate: '2026-10-08',
    durationWeeks: 2,
    scheduleSummary: 'Tuesdays & Thursdays, 18:30 - 20:00 (MNT)',
    meetingLink: 'https://meet.google.com/xyz-ment-mn1',
    status: 'open',
    createdAt: '2026-09-17T09:00:00Z',
  },
  {
    id: 'class-2',
    title: 'Intro to Python Game Dev: Build Your First 2D Arcade Game',
    description: 'Learn computational logic by building a functional arcade game from scratch using Python and Pygame. Hands-on coding every session!',
    mentorId: 'user-current',
    mentorName: 'Temuulen Batbayar',
    mentorTier: 'SENIOR_MENTOR',
    mentorSchool: 'School No. 1, Ulaanbaatar',
    subject: 'Computer Science',
    curriculum: 'Practical Engineering',
    maxSeats: 4,
    priceMnt: 35000,
    enrollmentMode: 'instant',
    missions: [
      {
        weekNumber: 1,
        title: 'Pygame Setup & Sprite Animation',
        description: 'Initialize graphics window, handle input events, and animate sprites with delta time.',
        deliverablePrompt: 'Submit working Python script with controllable player character.',
      },
      {
        weekNumber: 2,
        title: 'Collision Physics & Score Architecture',
        description: 'Build bounding box collisions, particle effects, and game over states.',
        deliverablePrompt: 'Submit GitHub repository link of complete 2D arcade game.',
      },
    ],
    enrolledStudents: [
      {
        id: 'std-3',
        name: 'Tselmeg Erdene',
        school: 'Darkhan 4th High School',
        location: 'Darkhan-Uul Aimag',
        grade: '10th Grade',
        enrolledAt: '2026-09-18T12:00:00Z',
        status: 'confirmed',
      },
      {
        id: 'std-4',
        name: 'Bilig Bayaraa',
        school: 'School No. 11, Ulaanbaatar',
        location: 'Ulaanbaatar - Chingeltei',
        grade: '9th Grade',
        enrolledAt: '2026-09-19T08:00:00Z',
        status: 'confirmed',
      },
      {
        id: 'std-5',
        name: 'Oyunaa Lkhagva',
        school: 'Dornod High School No. 1',
        location: 'Dornod Aimag',
        grade: '10th Grade',
        enrolledAt: '2026-09-20T03:00:00Z',
        status: 'confirmed',
      },
    ],
    startDate: '2026-09-26',
    endDate: '2026-10-10',
    durationWeeks: 2,
    scheduleSummary: 'Mondays & Fridays, 17:00 - 18:30 (MNT)',
    meetingLink: 'https://meet.google.com/tem-game-dev',
    status: 'open',
    createdAt: '2026-09-16T11:00:00Z',
  },
  {
    id: 'class-3',
    title: 'National Physics Olympiad: Advanced Circuit Analysis & DC Bridges',
    description: 'Intensive 2-student micro-pod tackling Wheatstone bridges, Kirchhoff loops, and non-linear circuit elements from national competitions.',
    mentorId: 'mentor-2',
    mentorName: 'Bilguun Zorig',
    mentorTier: 'MASTER_MENTOR',
    mentorSchool: 'Mongolian University of Science & Technology (MUST)',
    subject: 'Physics',
    curriculum: 'National Olympiad',
    maxSeats: 2,
    priceMnt: 0,
    enrollmentMode: 'application',
    missions: [
      {
        weekNumber: 1,
        title: 'Kirchhoff Mesh Analysis in Complex Symmetry',
        description: 'Solve multi-loop cube and infinite ladder resistor networks.',
        deliverablePrompt: 'Submit written proofs for 5 olympiad ladder circuits.',
      },
      {
        weekNumber: 2,
        title: 'Wheatstone & Non-Linear Diodes',
        description: 'Balance bridge circuits with temperature-dependent resistors.',
        deliverablePrompt: 'Submit lab analysis or simulation screenshots.',
      },
      {
        weekNumber: 3,
        title: 'Olympiad Final Mock Exam',
        description: 'Timed full-length physics circuit analysis exam.',
        deliverablePrompt: 'Submit full exam solutions PDF.',
      },
    ],
    enrolledStudents: [
      {
        id: 'user-current',
        name: 'Temuulen Batbayar',
        school: 'School No. 1, Ulaanbaatar',
        location: 'Ulaanbaatar - Sukhbaatar District',
        grade: '12th Grade',
        enrolledAt: '2026-09-19T16:00:00Z',
        status: 'confirmed',
      },
    ],
    startDate: '2026-09-28',
    endDate: '2026-10-19',
    durationWeeks: 3,
    scheduleSummary: 'Wednesdays & Saturdays, 19:00 - 20:30 (MNT)',
    meetingLink: 'https://meet.google.com/phys-olymp-mn',
    status: 'open',
    createdAt: '2026-09-15T15:00:00Z',
  },
  {
    id: 'class-4',
    title: 'Competitive Programming: Graph Trees & Dynamic Programming',
    description: 'Algorithms sprint for students preparing for the National Informatics Olympiad and International Olympiad in Informatics (IOI).',
    mentorId: 'mentor-3',
    mentorName: 'Nomin Erdene',
    mentorTier: 'NATIONAL_LAUREATE',
    mentorSchool: 'National University of Mongolia (NUM)',
    subject: 'Informatics',
    curriculum: 'National Olympiad',
    maxSeats: 8,
    priceMnt: 50000,
    enrollmentMode: 'application',
    missions: [
      {
        weekNumber: 1,
        title: 'Binary Lifting & Lowest Common Ancestor (LCA)',
        description: 'Tree traversal algorithms and fast queries.',
        deliverablePrompt: 'Submit Codeforces / Spoj problem submissions.',
      },
      {
        weekNumber: 2,
        title: 'Tree DP & Rerooting Techniques',
        description: 'Dynamic programming on trees with subtrees and parents.',
        deliverablePrompt: 'Submit AC code for 4 tree DP contest tasks.',
      },
      {
        weekNumber: 3,
        title: 'Heavy-Light Decomposition (HLD)',
        description: 'Segment trees over tree paths.',
        deliverablePrompt: 'Submit HLD template and solved national olympiad problem.',
      },
    ],
    enrolledStudents: [
      {
        id: 'std-6',
        name: 'Khangai Davaadorj',
        school: 'Shine Ue School',
        location: 'Ulaanbaatar - Khan-Uul',
        grade: '11th Grade',
        enrolledAt: '2026-09-16T10:00:00Z',
        status: 'confirmed',
      },
      {
        id: 'std-7',
        name: 'Ariunbold Batsukh',
        school: 'Bayan-Ulgii Turkish High School',
        location: 'Bayan-Ölgii Aimag',
        grade: '12th Grade',
        enrolledAt: '2026-09-17T11:00:00Z',
        status: 'confirmed',
      },
      {
        id: 'std-8',
        name: 'Naranbat Gantulga',
        school: 'School No. 1',
        location: 'Ulaanbaatar',
        grade: '11th Grade',
        enrolledAt: '2026-09-18T09:00:00Z',
        status: 'confirmed',
      },
      {
        id: 'std-9',
        name: 'Misheel Purev',
        school: 'Erdenet 14th High School',
        location: 'Orkhon Aimag',
        grade: '10th Grade',
        enrolledAt: '2026-09-19T10:00:00Z',
        status: 'confirmed',
      },
    ],
    startDate: '2026-10-01',
    endDate: '2026-10-22',
    durationWeeks: 3,
    scheduleSummary: 'Saturdays & Sundays, 14:00 - 16:00 (MNT)',
    meetingLink: 'https://meet.google.com/ioi-prep-mn',
    status: 'open',
    createdAt: '2026-09-14T08:00:00Z',
  },
  {
    id: 'class-5',
    title: 'General 10th Grade Chemistry: Stoichiometry & Reaction Kinetics',
    description: 'Demystifying chemical balancing, mole calculations, and solution concentrations with visual explanations and practice quizzes.',
    mentorId: 'mentor-4',
    mentorName: 'Saruul Otgon',
    mentorTier: 'JUNIOR_MENTOR',
    mentorSchool: 'Darkhan 4th High School',
    subject: 'Chemistry',
    curriculum: 'Mongolian 12-Year',
    maxSeats: 4,
    priceMnt: 0,
    enrollmentMode: 'instant',
    missions: [
      {
        weekNumber: 1,
        title: 'Mole Calculations & Limiting Reactants',
        description: 'Solve 15 core stoichiometry calculation problems with detailed units.',
        deliverablePrompt: 'Submit photos of solved calculation sheets.',
      },
    ],
    enrolledStudents: [
      {
        id: 'std-10',
        name: 'Tsatsral Bold',
        school: 'Uvs High School No. 1',
        location: 'Uvs Aimag',
        grade: '10th Grade',
        enrolledAt: '2026-09-19T13:00:00Z',
        status: 'confirmed',
      },
    ],
    startDate: '2026-09-25',
    endDate: '2026-10-02',
    durationWeeks: 1,
    scheduleSummary: 'Wednesdays & Fridays, 16:00 - 17:30 (MNT)',
    meetingLink: 'https://meet.google.com/chem-10-mn',
    status: 'open',
    createdAt: '2026-09-18T10:00:00Z',
  },
];

export const INITIAL_DELIVERABLES: Deliverable[] = [
  {
    id: 'del-1',
    classId: 'class-2',
    studentId: 'std-3',
    studentName: 'Tselmeg Erdene',
    title: 'Space Invaders Arcade Clone in Python',
    urlOrNotes: 'https://github.com/tselmeg/space-invaders-pygame',
    mentorFeedback: 'Outstanding work on the collision detection and sprite animations! Verified.',
    status: 'approved',
    submittedAt: '2026-09-19T18:00:00Z',
    approvedAt: '2026-09-20T09:00:00Z',
  },
  {
    id: 'del-2',
    classId: 'class-2',
    studentId: 'std-4',
    studentName: 'Bilig Bayaraa',
    title: 'Flappy Bird Physics Simulator with Score Counter',
    urlOrNotes: 'https://github.com/bilig/flappy-bird-python',
    status: 'pending',
    submittedAt: '2026-09-20T04:15:00Z',
  },
  {
    id: 'del-3',
    classId: 'class-3',
    studentId: 'user-current',
    studentName: 'Temuulen Batbayar',
    title: 'Wheatstone Bridge Non-Linear Resistance Analysis',
    urlOrNotes: 'https://drive.google.com/file/d/circuit-analysis-temuulen.pdf',
    status: 'pending',
    submittedAt: '2026-09-20T06:00:00Z',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'MN-ACAD-2026-0091',
    mentorId: 'mentor-1',
    mentorName: 'Temuulen Bat-Erdene',
    mentorSchool: 'Orchlon International School / MIT Scholar',
    tier: 'NATIONAL_LAUREATE',
    totalHours: 32,
    studentsImpacted: 10,
    classTitle: 'Cambridge A-Level Mathematics & Advanced Mechanics Sprint',
    subject: 'Mathematics',
    sha256Hash: '4f8e62bc10583b289cf784e621147fa4167e91d84b2c124018863f8d689b9102',
    issuedDate: '2026-09-18',
    verificationUrl: 'https://mentor.mn/verify/MN-ACAD-2026-0091',
  },
  {
    id: 'MN-EDU-2026-7A4F',
    mentorId: 'user-current',
    mentorName: 'Temuulen Batbayar',
    mentorSchool: 'School No. 1, Ulaanbaatar',
    tier: 'SENIOR_MENTOR',
    totalHours: 18,
    studentsImpacted: 8,
    classTitle: 'Python Game Development & Computational Thinking Sprint',
    subject: 'Computer Science',
    sha256Hash: 'a7b98d249f3e5b8d21c4568897213459fa87123bcdef0123456789abcdef0123',
    issuedDate: '2026-09-15',
    verificationUrl: 'https://mentor.mn/verify/MN-EDU-2026-7A4F',
  },
  {
    id: 'MN-EDU-2026-9E2B',
    mentorId: 'mentor-3',
    mentorName: 'Nomin Erdene',
    mentorSchool: 'National University of Mongolia (NUM)',
    tier: 'NATIONAL_LAUREATE',
    totalHours: 85,
    studentsImpacted: 64,
    classTitle: 'Advanced Olympiad Graph Algorithms & Trees',
    subject: 'Informatics',
    sha256Hash: 'e4c2b9a718d345f091248ab76123459cdef0123456789abcdef0123456789abc',
    issuedDate: '2026-08-30',
    verificationUrl: 'https://mentor.mn/verify/MN-EDU-2026-9E2B',
  },
];

export const NATIONAL_TELEMETRY = {
  activeClasses: 28,
  totalStudentsTaught: 94,
  aimagsReached: 16,
  knowledgeMultiplier: '3.4x',
  urbanToRuralTransferRate: '42%',
  provincialDistribution: [
    { province: 'Ulaanbaatar', count: 48, percentage: 51 },
    { province: 'Khovd Aimag', count: 12, percentage: 13 },
    { province: 'Darkhan-Uul Aimag', count: 10, percentage: 11 },
    { province: 'Dornod Aimag', count: 8, percentage: 8 },
    { province: 'Bayan-Ölgii Aimag', count: 7, percentage: 7 },
    { province: 'Orkhon (Erdenet)', count: 5, percentage: 5 },
    { province: 'Other 15 Aimags', count: 4, percentage: 5 },
  ],
};
